version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
# new Super Server Port    
#      - 51663:51773
      - 51663:1972
      - 52663:52773
      - 53773
    volumes:
# no license reuquired for community kit    
#      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
